apiVersion: unleashctl/v1
kind: ContextField
metadata:
  name: subscriptionTier
spec:
  description: The user's subscription tier gold,silver,bronze
  stickiness: true
  legalValues:
    - value: gold
      description: Gold tier
    - value: silver
      description: Silver tier
    - value: bronze
      description: Bronze tier
